version: '3.1'

services:

        db:
                image: postgres
                restart: always 
                environment:
                         POSTGRES_PASSWORD: admin
                ports:
                         - 5433:5433

        adminer:
                image: adminer
                restart: always
                ports:
                        - 8085:8085
