version: '3.1'
services :
  db:
    image: postgres 
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: etudiant
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8081:8080

