version: '3.1'
services :
  db:
    image: postgres 
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: etudiant
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8085:8085

